import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title> facile - React UI components library </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/ui.ico" />
      </Head>
      <main>
        <h1>facile ui</h1>
      </main>
    </>
  );
}
