import Head from 'next/head';
import { Article, Anchor, Separator } from '@/components';

export default function Home() {
  return (
    <>
      <Head>
        <title> Facile UI - React components library </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta
          name="description"
          content="Facile UI is a React components library, built in top of React, using typescript and tailwind css, it offers a rich feature of
          highly customizable components"
        />
        <link rel="icon" href="/ui.ico" />
      </Head>
      <main className="p-9 w-full min-h-screen m-auto flex flex-col items-center justify-start">
        <Article className="w-[50%]">
          <h1 className="text-4xl font-bold text-center">
            Speed up your development process using highly customizable react
            components.
          </h1>
          <br />
          <p className="text-[20px] leading-9 italic text-justify">
            Facile UI is a components library, built in top of React, using
            typescript and tailwind css. Its main purpose is to speed up
            development process by providing templates for common components,
            all of which can be customized to project requirements. <br />
          </p>
          <div className="w-[30%] flex flex-col items-center justify-around h-auto gap-3 m-auto mt-4">
            <Anchor
              className="!w-full px-8 font-semibold"
              href="/get-started"
              variant="primary"
            >
              Get started
            </Anchor>
            <Anchor
              className="!w-full px-8 font-semibold"
              href="/get-started"
              variant="secondary"
            >
              Components overview
            </Anchor>
          </div>
          <p className="text-[18px] leading-9 italic text-center mt-6">
            Created and mantained by{' '}
            <Anchor
              className="text-[18px] italic"
              href="https://github.com/Amaury-Vasquez"
            >
              @amvasdev
            </Anchor>
          </p>
        </Article>
      </main>
    </>
  );
}
